data:
  name: 'VTCD_WithIrre'
  datapath: 'data/Project_AMA/180_P3M6.mat'
  weights_datapath: 'data/Project_AMA/Weights_180_0.1_0.25.mat'
  test_datapath: 'data/Project_AMA/20_P3M6.mat'
  weights_datapath_test: 'data/Project_AMA/Weights_20_0.1_0.25.mat'
  virtual_datapath: 'data/Project_AMA/VirtualData_180.mat'
  total_num: 180
  offset: 0
  n_sample: 180
  test_sample: 20
  inputDim: 3
  outputDim: 6

model:
  layers: [16, 24, 24, 32, 32]
  width: 64
  modes: 400
  fc_dim: 64
  activation: elu

train:
  batchsize: 20
  batchsize_virtual: 20
  epochs: 3000
  milestones: [150, 300, 450]
  base_lr: 0.0002
  scheduler_gamma: 1.0
  ic_loss: 1.0
  f_loss: 0.0000
  f_virtual_loss: 0.0000
  xy_loss: 1.0
  save_dir: 'AMARunner\Test_WithVirtual'
  save_name: 'AMA_WithVirtual.pt'

#  ckpt: 'checkpoints/PaperRunner/Test1/FES_125.pt'

log:
  project: 'VTCD_Test'
  group: 'gelu-eqn'