data:
  D: 4.8
  DiffLossSwitch: 'Off'
  GradNorm: 'Off'
  GradNorm_alpha: 0.25
  NoData: 'Off'
  OperatorType: PINO-MBD
  PerformanceSwitch: 'Off'
  Structure_datapath: data/Project_BSA/StructureInfo.mat
  VirtualSwitch: 'On'
  datapath: data/Project_BSA/150.mat
  inputDim: 7
  nSlice: 40
  n_sample: 150
  n_sample_virtual: 2000
  name: BSA
  nt: 1000
  offset: 0
  outputDim: 200
  sub: 1
  sub_t: 1
  test_datapath: data/Project_BSA/30.mat
  test_sample: 30
  total_num: 100
  virtual_datapath: data/Project_BSA/VirtualData_2000.mat
  weights_datapath: data/Project_BSA/Weights_PINO_150.mat
  weights_datapath_test: data/Project_BSA/Weights_Medium_30.mat
  weights_datapath_virtual: data/Project_BSA/Weights_PINO_Virtual.mat
log:
  group: gelu-eqn
  project: VTCD_Test
model:
  activation: elu
  fc_dim: 100
  layers:
  - 16
  - 24
  - 24
  - 32
  - 32
  modes: 300
  width: 72
train:
  LossFileName: eval2_GradNorm
  base_lr: 0.0005
  batchsize: 7
  batchsize_virtual: 100
  diff_loss: 1.0
  epochs: 300
  f_loss: 1.0
  fv_loss: 1.0
  ic_loss: 1.0
  milestones:
  - 150
  - 300
  - 450
  save_dir: BSARunner/Experiment4
  save_name: BSA.pt
  scheduler_gamma: 1.0
  xy_loss: 1.0
