data:
  name: 'VTCD_WithIrre'
  datapath: 'data/Project_FES/5000.mat'
  weights_datapath: 'data/Project_FES/Weights_PINO_5000.mat'
  test_datapath: 'data/Project_FES/1000.mat'
  weights_datapath_test: 'data/Project_FES/Weights_PINO_1000.mat'
  Structure_datapath: 'data/Project_FES/StructureInfo.mat'
  virtual_datapath: 'data/Project_FES/VirtualData_15000.mat'
  weights_datapath_virtual: 'data/Project_FES/Weights_PINO_Virtual.mat'
  total_num: 2500
  offset: 0
  n_sample: 2500
  n_sample_virtual: 15000
  test_sample: 1000
  nt: 1000
  nSlice: 0
  sub: 1
  sub_t: 1
  inputDim: 4
  outputDim: 24
  D: 0.95
  VirtualSwitch: 'Off'
  PerformanceSwitch: 'On'
  DiffLossSwitch: 'Off'
  OperatorType: 'PINO'

model:
  layers: [16, 24, 24, 32, 32]
  width: 72
  modes: 400
  fc_dim: 72
  activation: elu

train:
  batchsize: 250
  batchsize_virtual: 750
  epochs: 500
  milestones: [150, 300, 450]
  base_lr: 0.001
  scheduler_gamma: 1.0
  ic_loss: 1.0
  f_loss: 1.0
  fv_loss: 1.0
  diff_loss: 1.0
  xy_loss: 1.0
  save_dir: 'FESRunner\PINO'
  save_name: 'FES.pt'
  LossFileName: 'LossHistory'

#  ckpt: 'checkpoints/PaperRunner/Test1/FES_125.pt'

log:
  project: 'VTCD_Test'
  group: 'gelu-eqn'